name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'min'
          - 'lts'
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      julia-arch: "${{ matrix.arch }}"
      os: "${{ matrix.os }}"
    secrets: "inherit"
  docs:
    name: Documentation
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      coverage: false
    secrets: "inherit"
  runic:
    name: Runic
    uses: "SciML/.github/.github/workflows/runic.yml@v1"
    secrets: "inherit"
  spellcheck:
    name: Spell Check
    uses: "SciML/.github/.github/workflows/spellcheck.yml@v1"
    secrets: "inherit"
  downgrade:
    name: Downgrade
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "lts"
      skip: "Pkg,TOML"
    secrets: "inherit"
